name: 'Update Confluence'
description: 'Updates the onbase pod confluence page to reflect current variable inputs'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env: 
    ATLASSIAN_TOKEN: ${{ secrets.ATLASSIAN_TOKEN }}
    CONFLUENCE_PAGE: "TEST OnBase Pod Terraform Inputs" # will change to actual page when production ready: